name = "M4R-project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["M4RProject"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1174c6410e869f41da76961735d21766d20a9849"

[[lean_lib]]
name = "M4RProject"
